"""empty message

Revision ID: 09c6614b1cc8
Revises: 65a877e2d01d
Create Date: 2024-01-31 20:22:41.882504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c6614b1cc8'
down_revision = '65a877e2d01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('color_ojos', sa.String(length=50), nullable=False),
    sa.Column('color_cabello', sa.String(length=50), nullable=False),
    sa.Column('altura', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_personaje')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
