"""empty message

Revision ID: fd35cb99a9b2
Revises: b1df07f8e70f
Create Date: 2024-01-31 20:26:47.551827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd35cb99a9b2'
down_revision = 'b1df07f8e70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.Column('id_vehiculos', sa.Integer(), nullable=True),
    sa.Column('id_person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_person'], ['person.id'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculos'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
